// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.27.0
// source: chat.sql

package db

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const addMessage = `-- name: AddMessage :one
INSERT INTO messages (chat_id, sender_email, content) VALUES ($1, $2, $3)
RETURNING id, chat_id, content, sender_email, created_at
`

type AddMessageParams struct {
	ChatID      pgtype.UUID `json:"chat_id"`
	SenderEmail string      `json:"sender_email"`
	Content     string      `json:"content"`
}

func (q *Queries) AddMessage(ctx context.Context, db DBTX, arg AddMessageParams) (Message, error) {
	row := db.QueryRow(ctx, addMessage, arg.ChatID, arg.SenderEmail, arg.Content)
	var i Message
	err := row.Scan(
		&i.ID,
		&i.ChatID,
		&i.Content,
		&i.SenderEmail,
		&i.CreatedAt,
	)
	return i, err
}

const createChat = `-- name: CreateChat :one
INSERT INTO chats DEFAULT VALUES
RETURNING id, admin_email, is_group_chat
`

func (q *Queries) CreateChat(ctx context.Context, db DBTX) (Chat, error) {
	row := db.QueryRow(ctx, createChat)
	var i Chat
	err := row.Scan(&i.ID, &i.AdminEmail, &i.IsGroupChat)
	return i, err
}

const createChatAccess = `-- name: CreateChatAccess :one
INSERT INTO chat_accesses (chat_id, user_email) VALUES ($1, $2)
RETURNING chat_id, user_email
`

type CreateChatAccessParams struct {
	ChatID    pgtype.UUID `json:"chat_id"`
	UserEmail string      `json:"user_email"`
}

func (q *Queries) CreateChatAccess(ctx context.Context, db DBTX, arg CreateChatAccessParams) (ChatAccess, error) {
	row := db.QueryRow(ctx, createChatAccess, arg.ChatID, arg.UserEmail)
	var i ChatAccess
	err := row.Scan(&i.ChatID, &i.UserEmail)
	return i, err
}

const createChatWithAdmin = `-- name: CreateChatWithAdmin :one
INSERT INTO chats (admin_email) VALUES ($1)
RETURNING id, admin_email, is_group_chat
`

func (q *Queries) CreateChatWithAdmin(ctx context.Context, db DBTX, adminEmail pgtype.Text) (Chat, error) {
	row := db.QueryRow(ctx, createChatWithAdmin, adminEmail)
	var i Chat
	err := row.Scan(&i.ID, &i.AdminEmail, &i.IsGroupChat)
	return i, err
}

const deleteChatAccess = `-- name: DeleteChatAccess :exec
DELETE FROM chat_accesses WHERE chat_id = $1 AND user_email = $2
`

type DeleteChatAccessParams struct {
	ChatID    pgtype.UUID `json:"chat_id"`
	UserEmail string      `json:"user_email"`
}

func (q *Queries) DeleteChatAccess(ctx context.Context, db DBTX, arg DeleteChatAccessParams) error {
	_, err := db.Exec(ctx, deleteChatAccess, arg.ChatID, arg.UserEmail)
	return err
}

const deleteChatById = `-- name: DeleteChatById :exec
DELETE FROM chats WHERE id = $1
`

func (q *Queries) DeleteChatById(ctx context.Context, db DBTX, id pgtype.UUID) error {
	_, err := db.Exec(ctx, deleteChatById, id)
	return err
}

const deleteMessage = `-- name: DeleteMessage :exec
DELETE FROM messages WHERE id = $1
`

func (q *Queries) DeleteMessage(ctx context.Context, db DBTX, id int64) error {
	_, err := db.Exec(ctx, deleteMessage, id)
	return err
}

const getChatAccessesByEmail = `-- name: GetChatAccessesByEmail :many
SELECT chat_id, user_email FROM chat_accesses WHERE user_email = $1
`

func (q *Queries) GetChatAccessesByEmail(ctx context.Context, db DBTX, userEmail string) ([]ChatAccess, error) {
	rows, err := db.Query(ctx, getChatAccessesByEmail, userEmail)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ChatAccess
	for rows.Next() {
		var i ChatAccess
		if err := rows.Scan(&i.ChatID, &i.UserEmail); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getChatById = `-- name: GetChatById :one
SELECT id, admin_email, is_group_chat FROM chats WHERE id = $1 LIMIT 1
`

func (q *Queries) GetChatById(ctx context.Context, db DBTX, id pgtype.UUID) (Chat, error) {
	row := db.QueryRow(ctx, getChatById, id)
	var i Chat
	err := row.Scan(&i.ID, &i.AdminEmail, &i.IsGroupChat)
	return i, err
}

const getMessagesByChatId = `-- name: GetMessagesByChatId :many
SELECT id, chat_id, content, sender_email, created_at FROM messages WHERE chat_id = $1 ORDER BY created_at ASC
`

func (q *Queries) GetMessagesByChatId(ctx context.Context, db DBTX, chatID pgtype.UUID) ([]Message, error) {
	rows, err := db.Query(ctx, getMessagesByChatId, chatID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Message
	for rows.Next() {
		var i Message
		if err := rows.Scan(
			&i.ID,
			&i.ChatID,
			&i.Content,
			&i.SenderEmail,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateChat = `-- name: UpdateChat :exec
UPDATE chats SET admin_email = $2, is_group_chat = $3
WHERE id = $1
`

type UpdateChatParams struct {
	ID          pgtype.UUID `json:"id"`
	AdminEmail  pgtype.Text `json:"admin_email"`
	IsGroupChat bool        `json:"is_group_chat"`
}

func (q *Queries) UpdateChat(ctx context.Context, db DBTX, arg UpdateChatParams) error {
	_, err := db.Exec(ctx, updateChat, arg.ID, arg.AdminEmail, arg.IsGroupChat)
	return err
}
